# Generated by Django 3.2.2 on 2022-04-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_state', models.CharField(max_length=50)),
                ('user_country', models.CharField(max_length=50)),
                ('user_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
